version: '3.7'
services:
  mysql:
    image: ${IMAGE_MYSQL}
    restart: always
    volumes:
      - type: bind
        source: ./mysql/data
        target: /var/lib/mysql/data
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_USER: ${MYSQL_USER:-quay_app}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-quay}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-registry}

  redis:
    image: ${IMAGE_REDIS}
    restart: always
    volumes:
      - type: bind
        source: ./redis/data
        target: /var/lib/redis/data

  registry:
    image: ${IMAGE_QUAY}
    restart: always
    volumes:
      - type: bind
        source: ./registry/conf/stack
        target: /conf/stack
      - type: bind
        source: ./registry/datastorage
        target: /datastorage
      - type: bind
        source: ./registry/logo
        target: /static/img-inep
    ports:
      - "443:8443"
      - "80:8080"
    depends_on:
      - mysql
      - redis