version: "3.7"

services:
  mysql:
    image: ${MYSQL_IMAGE:-centos/mysql-56-centos7:latest}
    restart: always
    volumes:
      - type: bind
        source: ./mysql/data
        target: /var/lib/mysql/data
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_USER: ${MYSQL_USER:-quay_app}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-quay}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-registry}

  redis:
    image: ${REDIS_IMAGE:-centos/redis-32-centos7:latest}
    restart: always
    volumes:
      - type: bind
        source: ./redis/data
        target: /var/lib/redis/data

  registry:
    image: ${QUAY_IMAGE:-quay.io/redhat/quay:v3.1.3}
    restart: always
    volumes:
      - type: bind
        source: ./registry/config
        target: /conf/stack
      - type: bind
        source: ./registry/datastorage
        target: /datastorage
    ports:
      - "443:8443"
      - "80:8080"
    depends_on:
      - mysql
      - redis